apiVersion: wl.io/v1
kind: ODAG
metadata:
  name: etl-wide
  namespace: wl-system
spec:
  scheduler: heft
  retryPolicy:
    maxRetries: 2
  tasks:
    - name: extract
      image: 192.168.1.163:5000/multi-odag-task:latest
      command: ["python", "task.py"]
      dependencies: []
      resources:
        cpu: "200m"
        memory: "512Mi"
      dataSize: "300MB"
      runtime: 3
      constraints:
        nodeNames: [anrg-3]

    - name: clean-a
      image: 192.168.1.163:5000/multi-odag-task:latest
      command: ["python", "task.py"]
      dependencies: ["extract"]
      resources:
        cpu: "200m"
        memory: "640Mi"
      dataSize: "100MB"
      runtime: 5
      constraints:
        nodeNames: [anrg-3, anrg-4]

    - name: clean-b
      image: 192.168.1.163:5000/multi-odag-task:latest
      command: ["python", "task.py"]
      dependencies: ["extract"]
      resources:
        cpu: "200m"
        memory: "640Mi"
      dataSize: "100MB"
      runtime: 7
      constraints:
        nodeNames: [anrg-5, anrg-6]

    - name: clean-c
      image: 192.168.1.163:5000/multi-odag-task:latest
      command: ["python", "task.py"]
      dependencies: ["extract"]
      resources:
        cpu: "200m"
        memory: "640Mi"
      dataSize: "100MB"
      runtime: 4
      constraints:
        nodeNames: [anrg-4, anrg-6]

    - name: load
      image: 192.168.1.163:5000/multi-odag-task:latest
      command: ["python", "task.py"]
      dependencies: ["clean-a", "clean-b", "clean-c"]
      resources:
        cpu: "300m"
        memory: "512Mi"
      dataSize: "10MB"
      runtime: 6
      constraints:
        nodeNames: [anrg-3, anrg-5]
