apiVersion: dsf.io/v1
kind: ODAGTemplate
metadata:
  name: scale-odag-p2p-w4
  namespace: dsf-system
spec:
  description: 'Scalability eval: 4 workers, 50MB, 2-3 node choices per worker'
  scheduler: random
  profiling:
    enabled: false
  defaults:
    runtime: 2
    dataSize: '50000000'
  retention:
    maxRuns: 15
  tasks:
  - name: source
    image: 192.168.1.163:5000/scalability-eval:latest
    command:
    - python
    - odag-task.py
    dependencies: []
    dataSize: '50000000'
    runtime: 2
    env:
    - name: DSF_EVAL_DATA_SIZE
      value: '50000000'
    resources:
      cpu: 300m
      memory: 256Mi
    constraints:
      nodeNames:
      - anrg-3
  - name: worker-1
    image: 192.168.1.163:5000/scalability-eval:latest
    command:
    - python
    - odag-task.py
    dependencies:
    - source
    dataSize: '50000000'
    runtime: 2
    env:
    - name: DSF_EVAL_DATA_SIZE
      value: '50000000'
    resources:
      cpu: 300m
      memory: 256Mi
    constraints:
      nodeNames:
      - anrg-3
      - anrg-5
  - name: worker-2
    image: 192.168.1.163:5000/scalability-eval:latest
    command:
    - python
    - odag-task.py
    dependencies:
    - source
    dataSize: '50000000'
    runtime: 2
    env:
    - name: DSF_EVAL_DATA_SIZE
      value: '50000000'
    resources:
      cpu: 300m
      memory: 256Mi
    constraints:
      nodeNames:
      - anrg-3
      - anrg-5
      - anrg-6
  - name: worker-3
    image: 192.168.1.163:5000/scalability-eval:latest
    command:
    - python
    - odag-task.py
    dependencies:
    - source
    dataSize: '50000000'
    runtime: 2
    env:
    - name: DSF_EVAL_DATA_SIZE
      value: '50000000'
    resources:
      cpu: 300m
      memory: 256Mi
    constraints:
      nodeNames:
      - anrg-4
      - anrg-5
  - name: worker-4
    image: 192.168.1.163:5000/scalability-eval:latest
    command:
    - python
    - odag-task.py
    dependencies:
    - source
    dataSize: '50000000'
    runtime: 2
    env:
    - name: DSF_EVAL_DATA_SIZE
      value: '50000000'
    resources:
      cpu: 300m
      memory: 256Mi
    constraints:
      nodeNames:
      - anrg-4
      - anrg-5
  - name: sink
    image: 192.168.1.163:5000/scalability-eval:latest
    command:
    - python
    - odag-task.py
    dependencies:
    - worker-1
    - worker-2
    - worker-3
    - worker-4
    dataSize: '0'
    runtime: 1
    resources:
      cpu: 300m
      memory: 512Mi
    constraints:
      nodeNames:
      - anrg-4
      - anrg-5
